# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class ActionEnum(object):

    """Implementation of the 'Action' enum.

    Indicate the action (add or subtract) to be taken.Allowed values increase,
    decrease

    Attributes:
        INCREASE: TODO: type description here.
        DECREASE: TODO: type description here.

    """

    INCREASE = 'increase'

    DECREASE = 'decrease'

