# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class AggregatedByEnum(object):

    """Implementation of the 'aggregated_by' enum.

    TODO: type enum description here.

    Attributes:
        DAY: TODO: type description here.
        WEEK: TODO: type description here.
        MONTH: TODO: type description here.

    """

    DAY = 'day'

    WEEK = 'week'

    MONTH = 'month'

