# -*- coding: utf-8 -*-

"""
    pepipost.models.attributes

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

from ..api_helper import APIHelper
class Attributes:

    """Implementation of the 'Attributes' model.

    TODO: type model description here.

    Attributes:
        attributes (string): TODO: type description here.
    """

    def __init__(self,
                 attributes):
        """Constructor for the Attributes class"""

        # Initialize members of the class
        self.attributes = attributes


    def get_attributes(self):
        """Creates an instance of this model from a dictionary

        Args:
            JSON (string): A key value pair json string.

        Returns:
            dictionary : dictionary mapping of passed attributes

        """
        if self.attributes == "" or self.attributes == None:
            return None

        return APIHelper.json_deserialize(self.attributes)

        


