# -*- coding: utf-8 -*-

"""
    pepipost.models.attribute

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""


class Attribute(object):

    """Implementation of the 'Attribute' model.

    TODO: type model description here.

    Attributes:
        myname (string): TODO: type description here.
        age (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "myname":'myname',
        "age":'age'
    }

    def __init__(self,
                 myname=None,
                 age=None):
        """Constructor for the Attribute class"""

        # Initialize members of the class
        self.myname = myname
        self.age = age


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        myname = dictionary.get('myname')
        age = dictionary.get('age')

        # Return an object of this model
        return cls(myname,
                   age)


