# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class DeleteDomain(object):

    """Implementation of the 'delete domain' model.

    delete domain modal

    Attributes:
        domain (string): Name of the domain

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "domain":'domain'
    }

    def __init__(self,
                 domain=None):
        """Constructor for the DeleteDomain class"""

        # Initialize members of the class
        self.domain = domain


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        domain = dictionary.get('domain')

        # Return an object of this model
        return cls(domain)


