# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class DeleteSubacoount(object):

    """Implementation of the 'delete subacoount' model.

    Deletesubaccount modal

    Attributes:
        username (string): The username of the subaccount

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "username":'username'
    }

    def __init__(self,
                 username=None):
        """Constructor for the DeleteSubacoount class"""

        # Initialize members of the class
        self.username = username


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        username = dictionary.get('username')

        # Return an object of this model
        return cls(username)


