# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class DomainStruct(object):

    """Implementation of the 'DomainStruct' model.

    Domain Modal

    Attributes:
        domain (string): The domain you wish to include in the 'From' header
            of your emails.
        envelope_name (string): The subdomain which will be used for tracking
            opens, clicks and unsubscribe

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "domain":'domain',
        "envelope_name":'envelopeName'
    }

    def __init__(self,
                 domain=None,
                 envelope_name=None):
        """Constructor for the DomainStruct class"""

        # Initialize members of the class
        self.domain = domain
        self.envelope_name = envelope_name


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        domain = dictionary.get('domain')
        envelope_name = dictionary.get('envelopeName')

        # Return an object of this model
        return cls(domain,
                   envelope_name)


