# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class EmailStruct(object):

    """Implementation of the 'EmailStruct' model.

    To, CC  and Bcc email Address structure

    Attributes:
        name (string): Name of recipient
        email (string): Email of recipient

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name":'name',
        "email":'email'
    }

    def __init__(self,
                 name=None,
                 email=None):
        """Constructor for the EmailStruct class"""

        # Initialize members of the class
        self.name = name
        self.email = email


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get('name')
        email = dictionary.get('email')

        # Return an object of this model
        return cls(name,
                   email)


