# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class EnableOrDisableSubacoount(object):

    """Implementation of the 'enable or disable subacoount' model.

    EnableDisablesubaccount modal

    Attributes:
        username (string): The username of the subaccount
        disabled (bool): Flag to indicate whether the subaccount should be
            enabled or disabled.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "username":'username',
        "disabled":'disabled'
    }

    def __init__(self,
                 username=None,
                 disabled=None):
        """Constructor for the EnableOrDisableSubacoount class"""

        # Initialize members of the class
        self.username = username
        self.disabled = disabled


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        username = dictionary.get('username')
        disabled = dictionary.get('disabled')

        # Return an object of this model
        return cls(username,
                   disabled)


