# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class EventsEnum(object):

    """Implementation of the 'events' enum.

    TODO: type enum description here.

    Attributes:
        PROCESSED: TODO: type description here.
        SENT: TODO: type description here.
        OPEN: TODO: type description here.
        CLICK: TODO: type description here.
        UNSUBSCRIBE: TODO: type description here.
        BOUNCE: TODO: type description here.
        SOFTBOUNCE: TODO: type description here.
        SPAM: TODO: type description here.
        INVALID: TODO: type description here.
        DROPPED: TODO: type description here.
        HARDBOUNCE: TODO: type description here.

    """

    PROCESSED = 'processed'

    SENT = 'sent'

    OPEN = 'open'

    CLICK = 'click'

    UNSUBSCRIBE = 'unsubscribe'

    BOUNCE = 'bounce'

    SOFTBOUNCE = 'softbounce'

    SPAM = 'spam'

    INVALID = 'invalid'

    DROPPED = 'dropped'

    HARDBOUNCE = 'hardbounce'

