# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class From(object):

    """Implementation of the 'From' model.

    Email address representing the sender of the mail

    Attributes:
        email (string): TODO: type description here.
        name (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "email":'email',
        "name":'name'
    }

    def __init__(self,
                 email=None,
                 name=None):
        """Constructor for the From class"""

        # Initialize members of the class
        self.email = email
        self.name = name


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        email = dictionary.get('email')
        name = dictionary.get('name')

        # Return an object of this model
        return cls(email,
                   name)


