# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class RemoveEmailOrDomainToSuppressionList(object):

    """Implementation of the 'Remove email or domain to Suppression list' model.

    Remove Suppression modal

    Attributes:
        domain (string): List one or more recipient domains to be removed from
            the suppression list here. <br>\nComma separate the values to
            suppress multiple recipient domains.
        email (string): List one or more email addresses to be removed from
            the suppression list here. <br>\nComma separate the values to
            suppress multiple email addresses.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "domain":'domain',
        "email":'email'
    }

    def __init__(self,
                 domain=None,
                 email=None):
        """Constructor for the RemoveEmailOrDomainToSuppressionList class"""

        # Initialize members of the class
        self.domain = domain
        self.email = email


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        domain = dictionary.get('domain')
        email = dictionary.get('email')

        # Return an object of this model
        return cls(domain,
                   email)


