# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class SortEnum(object):

    """Implementation of the 'sort' enum.

    TODO: type enum description here.

    Attributes:
        ASC: TODO: type description here.
        DESC: TODO: type description here.

    """

    ASC = 'asc'

    DESC = 'desc'

