# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class TimeperiodEnum(object):

    """Implementation of the 'Timeperiod' enum.

    The periodic \n\nAllowed values  \"daily\", \"weekly\", \"monhtly\"

    Attributes:
        DAILY: TODO: type description here.
        WEEKLY: TODO: type description here.
        MONHTLY: TODO: type description here.

    """

    DAILY = 'daily'

    WEEKLY = 'weekly'

    MONHTLY = 'monhtly'

