# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class TypeEnum(object):

    """Implementation of the 'Type' enum.

    TODO: type enum description here.

    Attributes:
        AMP: TODO: type description here.
        HTML: TODO: type description here.

    """

    AMP = 'amp'

    HTML = 'html'

