# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class UpdateCredisOfSubaccount(object):

    """Implementation of the 'Update Credis of subaccount' model.

    UpdateCreditaccount modal

    Attributes:
        username (string): The username of the subaccount
        action (ActionEnum): Indicate the action (add or subtract) to be
            taken.Allowed values increase, decrease
        amount (int): Amount of credits

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "username":'username',
        "action":'action',
        "amount":'amount'
    }

    def __init__(self,
                 username=None,
                 action=None,
                 amount=None):
        """Constructor for the UpdateCredisOfSubaccount class"""

        # Initialize members of the class
        self.username = username
        self.action = action
        self.amount = amount


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        username = dictionary.get('username')
        action = dictionary.get('action')
        amount = dictionary.get('amount')

        # Return an object of this model
        return cls(username,
                   action,
                   amount)


