# -*- coding: utf-8 -*-

"""
   PepipostAPIV10Lib.Configuration

   This file was automatically generated by APIMATIC v2.0 on 04/15/2016
"""

class Configuration(object):
    # The base Uri for API calls
    BASE_URI = "https://api.pepipost.com"


