# -*- coding: utf-8 -*-

"""
   PepipostAPIV10Lib.APIException

   This file was automatically generated by APIMATIC v2.0 on 04/15/2016
"""

class LazyProperty(object):

    """A decorator class for lazy instantiation."""

    def __init__(self,fget):
        self.fget = fget
        self.func_name = fget.__name__

    def __get__(self,obj,cls):
        if obj is None:
            return None
        value = self.fget(obj)
        setattr(obj,self.func_name,value)
        return value