"""
    PepipostAPIV10Lib

    This file was automatically generated by APIMATIC BETA v2.0 on 04/15/2016
"""
from PepipostAPIV10Lib.Models import *
from PepipostAPIV10Lib.Controllers import *
from PepipostAPIV10Lib.Decorators import *
from PepipostAPIV10Lib.APIException import *

class PepipostAPIV10Client(object):

    @LazyProperty
    def email_controller(self):
        return EmailController()



