# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from pepipost.decorators import lazy_property
from pepipost.configuration import Configuration
from pepipost.controllers.send_controller import SendController


class PepipostClient(object):

    config = Configuration

    @lazy_property
    def send(self):
        return SendController()


    def __init__(self,
                 api_key='4D51B3ECA2D4ED3A67E4E043B3F1A4D1'):
        if api_key is not None:
            Configuration.api_key = api_key

