# -*- coding: utf-8 -*-

"""
   PepipostAPIV10Lib.Models.Attributes
 
   This file was automatically generated by APIMATIC v2.0 on 04/15/2016
"""
from PepipostAPIV10Lib.APIHelper import APIHelper

class Attributes(object):

    """Implementation of the 'attributes' model.

    TODO: type model description here.

    Attributes:
        name (list of string): TODO: type description here.
        regid (list of string): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the Attributes class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    NAME -- list of string -- Sets the attribute name
                    REGID -- list of string -- Sets the attribute regid
        
        """
        # Set all of the parameters to their default values
        self.name = None
        self.regid = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "NAME": "name",
            "REGID": "regid",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "name": "NAME",
            "regid": "REGID",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)