# -*- coding: utf-8 -*-

"""
   PepipostAPIV10Lib.Models.Emailv1
 
   This file was automatically generated by APIMATIC v2.0 on 04/15/2016
"""
from PepipostAPIV10Lib.APIHelper import APIHelper
from PepipostAPIV10Lib.Models.EmailDetails import EmailDetails
from PepipostAPIV10Lib.Models.Settings import Settings
from PepipostAPIV10Lib.Models.Attributes import Attributes
from PepipostAPIV10Lib.Models.Files import Files

class Emailv1(object):

    """Implementation of the 'Emailv1' model.

    TODO: type model description here.

    Attributes:
        api_key (string): Your secret API Key
        email_details (EmailDetails): TODO: type description here.
        x_apiheader (list of string): TODO: type description here.
        settings (Settings): TODO: type description here.
        recipients (list of string): TODO: type description here.
        attributes (Attributes): TODO: type description here.
        files (Files): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the Emailv1 class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    api_key -- string -- Sets the attribute api_key
                    email_details -- EmailDetails -- Sets the attribute email_details
                    X-APIHEADER -- list of string -- Sets the attribute x_apiheader
                    settings -- Settings -- Sets the attribute settings
                    recipients -- list of string -- Sets the attribute recipients
                    attributes -- Attributes -- Sets the attribute attributes
                    files -- Files -- Sets the attribute files
        
        """
        # Set all of the parameters to their default values
        self.api_key = None
        self.email_details = None
        self.x_apiheader = None
        self.settings = None
        self.recipients = None
        self.attributes = None
        self.files = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "api_key": "api_key",
            "email_details": "email_details",
            "X-APIHEADER": "x_apiheader",
            "settings": "settings",
            "recipients": "recipients",
            "attributes": "attributes",
            "files": "files",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

            # Other objects also need to be initialised properly
            if "email_details" in kwargs:
                self.email_details = EmailDetails(**kwargs["email_details"])

            # Other objects also need to be initialised properly
            if "settings" in kwargs:
                self.settings = Settings(**kwargs["settings"])

            # Other objects also need to be initialised properly
            if "attributes" in kwargs:
                self.attributes = Attributes(**kwargs["attributes"])

            # Other objects also need to be initialised properly
            if "files" in kwargs:
                self.files = Files(**kwargs["files"])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "api_key": "api_key",
            "email_details": "email_details",
            "x_apiheader": "X-APIHEADER",
            "settings": "settings",
            "recipients": "recipients",
            "attributes": "attributes",
            "files": "files",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)