# -*- coding: utf-8 -*-

"""
   PepipostAPIV10Lib.Models.Settings
 
   This file was automatically generated by APIMATIC v2.0 on 04/15/2016
"""
from PepipostAPIV10Lib.APIHelper import APIHelper

class Settings(object):

    """Implementation of the 'settings' model.

    TODO: type model description here.

    Attributes:
        footer (bool): TODO: type description here.
        clicktrack (bool): TODO: type description here.
        opentrack (bool): TODO: type description here.
        unsubscribe (bool): TODO: type description here.
        bcc (string): TODO: type description here.
        attachmentid (string): TODO: type description here.
        template (int): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the Settings class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    footer -- bool -- Sets the attribute footer
                    clicktrack -- bool -- Sets the attribute clicktrack
                    opentrack -- bool -- Sets the attribute opentrack
                    unsubscribe -- bool -- Sets the attribute unsubscribe
                    bcc -- string -- Sets the attribute bcc
                    attachmentid -- string -- Sets the attribute attachmentid
                    template -- int -- Sets the attribute template
        
        """
        # Set all of the parameters to their default values
        self.footer = None
        self.clicktrack = None
        self.opentrack = None
        self.unsubscribe = None
        self.bcc = None
        self.attachmentid = None
        self.template = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "footer": "footer",
            "clicktrack": "clicktrack",
            "opentrack": "opentrack",
            "unsubscribe": "unsubscribe",
            "bcc": "bcc",
            "attachmentid": "attachmentid",
            "template": "template",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "footer": "footer",
            "clicktrack": "clicktrack",
            "opentrack": "opentrack",
            "unsubscribe": "unsubscribe",
            "bcc": "bcc",
            "attachmentid": "attachmentid",
            "template": "template",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)